name: kopeboy
favicon: null
layout_spectrum: 0.44325
typography_spectrum: 0.40098
title: Blog di Lorenzo Giovenali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-48841203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
