name: kopeboy
favicon: null
layout_spectrum: 0.18312902771867812
typography_spectrum: 0.34702822426334023
title: Blog di Lorenzo Giovenali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-48841203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06311509548686445
  lightness: 0.31221094634383917
  saturation: 0.03245340334251523
  rhythmicContrast: 0.8665636025834829
purpose: []
